name: Draft Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      base-ref:
        type: string
        default: ""

jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize version
        shell: bash
        run: |
          VERSION_TAG="$( (git describe --tags --exact-match HEAD || git rev-parse --short HEAD) | sed 's/\(.*\)-\(.*\)/\1.\2/g' )"
          echo "VERSION_TAG=${VERSION_TAG}" >> "$GITHUB_ENV"
          echo "VERSION=${VERSION_TAG#v}" >> "$GITHUB_ENV"

      - name: Update plugin version
        shell: bash
        run: sed -i 's|version="<VERSION>"|version="${{ env.VERSION }}"|g' app.cfg

      - name: Create artifact
        shell: bash
        run: |
          mkdir out/
          git archive --prefix="addons/limbo_console/" --output="out/limbo_console_${VERSION_TAG}.zip" ${{ github.ref }}

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          base-ref: ${{ inputs.base-ref }}

      - name: Draft Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: ${{ env.VERSION_TAG }}
          body: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          artifacts: "out/limbo_console_${{ env.VERSION_TAG }}.zip"
